### ISSUE TITLE
關於專案Course_222前端部分建議

### ISSUE THREAD

**Issue by Meilin410** [ywchiu/largitdata#2]
您好，我是一名剛接觸生物資訊的研究生，我需要閱讀大量的文獻資料，所以您的專案非常吸引我。
但是前端的代碼只能連結PDF網站，而大多數PDF文件我們會放在PC端文件或是google雲端硬碟。
我要如何修改前端代碼使其可以讀取PC路徑下或者雲端硬碟的PDF文檔。
能否請你試寫一個範本作為參考呢?

**Comment by ywchiu** [comment]
好呀，這星期錄一集

**Comment by Meilin410** [comment]
非常感謝，謝謝指教。


David Chiu ***@***.***> 於 2024年4月29日 週一 上午10:16 寫道：

**Comment by ywchiu** [comment]
看看這一集的做法歐

影片：  
https://www.largitdata.com/course/242/

程式碼： 
https://colab.research.google.com/github/ywchiu/largitdata/blob/master/code/Course_242.ipynb

**Comment by Meilin410** [comment]
收益良多，
我目前正在嘗試在實驗室的discord群組組建一套高效系統（本身純生物學背景，實驗室有一些生物資訊背景），
讓導師與同學有更多時間。您的方法無疑可以作爲一個基石。
十分謝謝您。

David Chiu ***@***.***> 於 2024年5月5日 週日 下午10:57寫道：
